import os
import sys
from pathlib import Path
from tts_service import generate_tts
from render_video import generate_video
import json
import time

def run_test_hook():
    """
    Step 4: Validation Test (3s Hook)
    Test syntax, music, and image sync for the ViralPostProduction module.
    """
    print("🚀 Running 3s Test Hook validation...")
    
    test_id = "test_hook_90"
    job_dir = Path("media/production") / test_id
    job_dir.makedirs(exist_ok=True, parents=True)
    
    hook_text = "On nous a menti sur l'origine de l'intelligence artificielle... Ce que vous allez voir a été enterré pendant 40 ans"
    
    # 1. Generate Voice (VoiceMaster)
    voice_path = job_dir / "voiceover.wav"
    # We use f5-tts for premium narrative voice as requested
    success = generate_tts(hook_text, str(voice_path), mode="f5-tts")
    
    if not success:
        print("❌ VoiceMaster failed. Please check FAL_KEY or local dependencies.")
        return

    # 2. Mock some images/clips if they don't exist
    # Real test would need 18 images for 90s, but here we test the "Hook" (3-5s)
    # We'll just copy existing images if any, or use placeholders
    img_dir = job_dir
    clips_dir = job_dir / "clips_video"
    clips_dir.mkdir(exist_ok=True)
    
    # We need at least one clip for render_video.py to work
    # In a real run, this would be generated by production.py
    # For the test, we assume the user wants to check the PIRE montage logic
    
    print(f"✅ Voice generated at {voice_path}")
    print("Next step: Run full 'production.py' with this ID to test visual sync.")
    
    # Triggering render_video logic mock
    # generate_video(str(job_dir))

if __name__ == "__main__":
    run_test_hook()
