import os
import json
import sqlite3
from pathlib import Path

# --- IMPORTANT: Requirements ---
# Needs tiktok-uploader installed via pip.
# Needs a 'tiktok_cookies.txt' file in the backend/ folder.
# You can generate this cookies file using the browser extension 'Get cookies.txt' 
# while logged into tiktok.com, or using 'tiktok-uploader auth' command.

def upload_to_tiktok(script_id_num: int):
    """
    Actually performs the upload of the generated video for script_id.
    Reads caption from tiktok_data.json inside job dir.
    """
    try:
        base_dir = Path(__file__).parent
        db_path = base_dir / "db.sqlite3"
        job_dir = base_dir / "media" / "production" / f"db_{script_id_num}"
        video_path = job_dir / "final_output.mp4"
        data_path = job_dir / "tiktok_data.json"
        cookie_path = base_dir / "tiktok_cookies.txt"

        if not video_path.exists():
            return f"Error: Video file not found at {video_path}"
        
        caption = "Auto-generated by iM-System #AISelfHosting #DarkTech"
        if data_path.exists():
            with open(data_path, "r") as f:
                caption = json.load(f).get("caption", caption)

        if not cookie_path.exists():
             return "Error: tiktok_cookies.txt missing. Cannot upload without session cookies."

        print(f"Uploading script #{script_id_num} to TikTok with caption: {caption}")
        
        # We use the CLI or library for upload
        # Warning: This is a blocking call and might take a minute
        from tiktok_uploader.upload import upload_video
        
        success = upload_video(
            filename=str(video_path),
            description=caption,
            cookies=str(cookie_path)
        )

        if success:
            # Update DB status
            conn = sqlite3.connect(str(db_path))
            cur = conn.cursor()
            cur.execute("UPDATE script_inbox SET status = 'published' WHERE id = ?", (script_id_num,))
            conn.commit()
            conn.close()
            return "SUCCESS: Published to TikTok!"
        else:
            return "FAILED: TikTok upload error (Cookies expired or connection error)."

    except Exception as e:
        print(f"TikTok Automation Error: {e}")
        return f"Error: {e}"

if __name__ == "__main__":
    import sys
    if len(sys.argv) > 1:
        print(upload_to_tiktok(int(sys.argv[1])))
