import React, { useState, useEffect } from 'react';
import { Film, Download, Info, Calendar, Hash, BarChart3, ChevronRight, Play } from 'lucide-react';
import { Badge } from '../components/ui';

const Gallery = () => {
    const [videos, setVideos] = useState([]);
    const [selectedVideo, setSelectedVideo] = useState(null);
    const [loading, setLoading] = useState(true);

    useEffect(() => {
        const fetchVideos = async () => {
            try {
                const apiUrl = import.meta.env.VITE_API_URL || 'http://localhost:5656';
                const response = await fetch(`${apiUrl}/api/contents`);
                const data = await response.json();
                // Filter for 'Posted' column
                const postedVideos = data.filter(v => v.column === 'Posted');
                // Sort by date (newest first)
                postedVideos.sort((a, b) => new Date(b.created_at) - new Date(a.created_at));
                setVideos(postedVideos);
            } catch (error) {
                console.error("Failed to fetch gallery videos:", error);
            } finally {
                setLoading(false);
            }
        };
        fetchVideos();
    }, []);

    const formatDate = (dateStr) => {
        if (!dateStr) return "N/A";
        const date = new Date(dateStr);
        return date.toLocaleDateString('fr-FR', { day: '2-digit', month: 'short', year: 'numeric', hour: '2-digit', minute: '2-digit' });
    };

    return (
        <div className="space-y-8 animate-in fade-in duration-700">
            <header className="flex justify-between items-end">
                <div>
                    <h1 className="text-3xl font-bold text-white tracking-tight flex items-center gap-3">
                        <Film className="h-8 w-8 text-cyan-400" />
                        Video Gallery
                    </h1>
                    <p className="text-gray-400 mt-2">Archives of all viral artifacts generated by the iM Swarm.</p>
                </div>
                <div className="text-right">
                    <Badge variant="cyber" className="text-lg px-4 py-1">{videos.length} Videos</Badge>
                </div>
            </header>

            {loading ? (
                <div className="h-64 flex items-center justify-center">
                    <div className="animate-spin rounded-full h-12 w-12 border-t-2 border-b-2 border-cyan-500"></div>
                </div>
            ) : videos.length > 0 ? (
                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6">
                    {videos.map(video => (
                        <div
                            key={video.id}
                            className="glass-card group flex flex-col hover:border-cyan-500/50 transition-all duration-300 overflow-hidden shadow-lg hover:shadow-cyan-500/10"
                        >
                            {/* Video Preview / Placeholder */}
                            <div className="relative aspect-[9/16] bg-navy-900 border-b border-gray-800 overflow-hidden">
                                <video
                                    src={`${import.meta.env.VITE_API_URL || 'http://localhost:5656'}/media/production/${video.id}/final_output.mp4`}
                                    className="w-full h-full object-cover opacity-80 group-hover:opacity-100 transition-opacity"
                                    muted
                                    onMouseOver={e => e.target.play()}
                                    onMouseOut={e => { e.target.pause(); e.target.currentTime = 0; }}
                                />
                                <div className="absolute inset-0 flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity pointer-events-none">
                                    <div className="bg-cyan-500/20 backdrop-blur-md p-4 rounded-full border border-cyan-400/50">
                                        <Play className="h-8 w-8 text-cyan-400 fill-cyan-400" />
                                    </div>
                                </div>
                                <div className="absolute bottom-3 left-3 flex gap-2">
                                    <Badge className="bg-black/60 backdrop-blur-md text-[10px] border-none">{formatDate(video.created_at)}</Badge>
                                </div>
                            </div>

                            <div className="p-4 flex-1 flex flex-col gap-3">
                                <h3 className="font-bold text-white text-lg leading-tight line-clamp-2">{video.title}</h3>

                                <div className="flex gap-4">
                                    <div className="flex flex-col">
                                        <span className="text-[10px] text-gray-500 font-bold uppercase tracking-widest">Viral</span>
                                        <span className="text-cyan-400 font-black text-lg">{video.viralScore}%</span>
                                    </div>
                                    <div className="flex flex-col border-l border-gray-800 pl-4">
                                        <span className="text-[10px] text-gray-500 font-bold uppercase tracking-widest">Revenue</span>
                                        <span className="text-emerald-400 font-black text-lg">{video.moneyScore}%</span>
                                    </div>
                                </div>

                                <div className="flex flex-wrap gap-1.5 mt-1">
                                    {video.keywords?.split(',').slice(0, 3).map((kw, idx) => (
                                        <span key={idx} className="text-[10px] text-gray-400 flex items-center gap-1 bg-navy-900/50 px-2 py-0.5 rounded border border-gray-800">
                                            <Hash className="h-2.5 w-2.5 text-cyan-500" /> {kw.trim()}
                                        </span>
                                    ))}
                                </div>

                                <div className="flex gap-2 mt-auto pt-4 border-t border-gray-800/50">
                                    <button
                                        onClick={() => setSelectedVideo(video)}
                                        className="flex-1 flex items-center justify-center gap-2 bg-navy-800 hover:bg-navy-700 text-gray-300 text-xs font-bold py-2.5 rounded-lg border border-gray-700 transition-colors"
                                    >
                                        <Info className="h-3.5 w-3.5 text-cyan-400" /> Details
                                    </button>
                                    <a
                                        href={`${import.meta.env.VITE_API_URL || 'http://localhost:5656'}/media/production/${video.id}/final_output.mp4`}
                                        download={`iM_System_${video.id}.mp4`}
                                        className="flex items-center justify-center bg-cyan-600 hover:bg-cyan-500 text-white p-2.5 rounded-lg transition-colors shadow-lg shadow-cyan-600/20"
                                    >
                                        <Download className="h-4 w-4" />
                                    </a>
                                </div>
                            </div>
                        </div>
                    ))}
                </div>
            ) : (
                <div className="h-[50vh] flex flex-col items-center justify-center border-2 border-dashed border-navy-800 rounded-3xl space-y-4">
                    <div className="bg-navy-800 p-6 rounded-full">
                        <Film className="h-12 w-12 text-gray-600" />
                    </div>
                    <div className="text-center">
                        <h3 className="text-xl font-bold text-white">No viral videos yet</h3>
                        <p className="text-gray-500 max-w-sm mt-2">Generate and post videos in the Studio to see them appear in your magnificent gallery.</p>
                    </div>
                </div>
            )}

            {/* Video Detail Modal */}
            {selectedVideo && (
                <div className="fixed inset-0 z-[100] flex items-center justify-center p-4 animate-in fade-in zoom-in duration-300">
                    <div className="absolute inset-0 bg-navy-950/80 backdrop-blur-xl" onClick={() => setSelectedVideo(null)}></div>
                    <div className="bg-navy-900 border border-cyan-500/30 rounded-3xl w-full max-w-5xl max-h-[90vh] overflow-hidden shadow-2xl relative z-10 flex flex-col md:flex-row">
                        <button
                            onClick={() => setSelectedVideo(null)}
                            className="absolute top-6 right-6 z-20 bg-black/50 hover:bg-black/80 text-white p-2 rounded-full backdrop-blur-md transition-colors"
                        >
                            <ChevronRight className="h-6 w-6 rotate-45" />
                        </button>

                        {/* Left: Video Player */}
                        <div className="md:w-1/2 bg-black flex items-center justify-center">
                            <video
                                src={`${import.meta.env.VITE_API_URL || 'http://localhost:5656'}/media/production/${selectedVideo.id}/final_output.mp4`}
                                className="w-full h-full max-h-[80vh] md:max-h-none object-contain"
                                controls
                                autoPlay
                            />
                        </div>

                        {/* Right: Content & Metadata */}
                        <div className="md:w-1/2 p-8 overflow-y-auto custom-scrollbar flex flex-col gap-6">
                            <div>
                                <Badge className="mb-2 bg-cyan-500/10 text-cyan-400 border-cyan-500/20">Generation Success</Badge>
                                <h2 className="text-3xl font-black text-white leading-tight">{selectedVideo.title}</h2>
                                <p className="text-gray-400 flex items-center gap-2 mt-2 text-sm italic">
                                    <Calendar className="h-3.5 w-3.5" /> Published on {formatDate(selectedVideo.created_at)}
                                </p>
                            </div>

                            <div className="grid grid-cols-3 gap-4">
                                <div className="glass-card bg-navy-800/30 p-4 border border-gray-800">
                                    <span className="text-[10px] text-gray-500 font-bold uppercase tracking-widest block mb-1">Viral Power</span>
                                    <span className="text-2xl font-black text-cyan-400">{selectedVideo.viralScore}%</span>
                                </div>
                                <div className="glass-card bg-navy-800/30 p-4 border border-gray-800">
                                    <span className="text-[10px] text-gray-500 font-bold uppercase tracking-widest block mb-1">Monetization</span>
                                    <span className="text-2xl font-black text-emerald-400">{selectedVideo.moneyScore}%</span>
                                </div>
                                <div className="glass-card bg-navy-800/30 p-4 border border-gray-800">
                                    <span className="text-[10px] text-gray-500 font-bold uppercase tracking-widest block mb-1">Cost Est.</span>
                                    <span className="text-2xl font-black text-white">${selectedVideo.costEstimate?.toFixed(2) || "0.05"}</span>
                                </div>
                            </div>

                            <div>
                                <h4 className="text-xs font-bold text-gray-400 uppercase tracking-widest mb-3 flex items-center gap-2">
                                    <BarChart3 className="h-3.5 w-3.5 text-cyan-500" /> Full Script Content
                                </h4>
                                <div className="bg-navy-950/50 p-6 rounded-2xl border border-gray-800 text-gray-300 text-sm leading-relaxed whitespace-pre-wrap font-medium">
                                    {selectedVideo.script}
                                </div>
                            </div>

                            <div>
                                <h4 className="text-xs font-bold text-gray-400 uppercase tracking-widest mb-3">Hashtags & Meta</h4>
                                <div className="flex flex-wrap gap-2">
                                    {selectedVideo.keywords?.split(',').map((kw, i) => (
                                        <Badge key={i} variant="outline" className="border-gray-800 text-gray-400">#{kw.trim().toLowerCase().replace(/\s+/g, '')}</Badge>
                                    ))}
                                </div>
                            </div>

                            <div className="mt-4 flex gap-4">
                                <a
                                    href={`${import.meta.env.VITE_API_URL || 'http://localhost:5656'}/media/production/${selectedVideo.id}/final_output.mp4`}
                                    download
                                    className="flex-1 flex items-center justify-center gap-2 bg-gradient-to-r from-cyan-600 to-blue-600 hover:from-cyan-500 hover:to-blue-500 text-white font-bold py-4 rounded-2xl shadow-xl shadow-cyan-600/20 transition-all uppercase tracking-widest text-xs"
                                >
                                    <Download className="h-4 w-4" /> Download Raw Video
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            )}
        </div>
    );
};

export default Gallery;
